//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace therapyDB.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addresses> addresses { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<meetings> meetings { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<room_times> room_times { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<therapist_treatments> therapist_treatments { get; set; }
        public virtual DbSet<therapists> therapists { get; set; }
        public virtual DbSet<times> times { get; set; }
        public virtual DbSet<treatments> treatments { get; set; }
    }
}
