//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace therapyDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetings
    {
        public int meet_id { get; set; }
        public int patient_id { get; set; }
        public int room_time_id { get; set; }
        public int therapist_treatment_id { get; set; }
    
        public virtual patients patients { get; set; }
        public virtual room_times room_times { get; set; }
        public virtual therapist_treatments therapist_treatments { get; set; }
    }
}
