//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace therapyDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_times
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room_times()
        {
            this.meetings = new HashSet<meetings>();
        }
    
        public int rti_id { get; set; }
        public int room_id { get; set; }
        public int time_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetings> meetings { get; set; }
        public virtual rooms rooms { get; set; }
        public virtual times times { get; set; }
    }
}
